-- Enrich the existing clients table with the fields needed for the
-- canonical Scaled AI client list: contact info, priority rank, start
-- date, subscription date, integration flags, and hosting metadata.
-- The original `priority` (low/medium/high) bucket and `display_order`
-- columns stay so the Client Hub UI keeps working unchanged.

alter table public.clients
  add column if not exists contact_name text,
  add column if not exists contact_emails text[] not null default '{}',
  add column if not exists priority_rank integer,
  add column if not exists start_date date,
  add column if not exists subscription_date text,
  add column if not exists status text not null default 'active',
  add column if not exists did_build_website boolean,
  add column if not exists tawk_installed boolean,
  add column if not exists google_profile_automation boolean,
  add column if not exists domain_location text,
  add column if not exists hosting_location text;

create index if not exists clients_priority_rank_idx on public.clients (priority_rank);
create index if not exists clients_status_idx on public.clients (status);

-- Hard reset before seeding. client_resources rows cascade.
delete from public.clients;

-- Bucket helper: rank ≤ 5 → high, ≤ 15 → medium, else low. Keeps the
-- old text column populated so the legacy Hub UI surfaces clients in
-- a coarse-priority section even without reading the new rank.
insert into public.clients (
  id, name, website, contact_name, contact_emails,
  priority, priority_rank, display_order,
  start_date, subscription_date, status,
  did_build_website, tawk_installed, google_profile_automation,
  domain_location, hosting_location, notes
) values
('cl_villa_treatment',         'Villa Treatment Center',         'https://thevillatreatmentcenter.com/', 'Colin Mackey',                 ARRAY['cmackey@villarecoverynetwork.com','melissa@empowerrecoverynj.com'], 'high',   1,    100,  '2025-02-03', '1st',  'active',  true,  true,  true,  'GoDaddy',    null,         'Woodland Hills addiction & mental health.'),
('cl_villa_behavioral',        'Villa Behavioral Health',        'https://villabehavioralhealth.com/',   'Colin Mackey',                 ARRAY['cmackey@villarecoverynetwork.com','melissa@empowerrecoverynj.com'], 'high',   1,    110,  '2025-02-03', '1st',  'active',  true,  true,  true,  'GoDaddy',    null,         null),
('cl_villa_healing',           'Villa Healing Center',           'https://villahealingcenter.com/',      'Colin Mackey',                 ARRAY['cmackey@villarecoverynetwork.com','melissa@empowerrecoverynj.com'], 'high',   1,    120,  '2025-02-03', '1st',  'active',  true,  true,  true,  'GoDaddy',    null,         null),
('cl_villa_wellness',          'Villa Wellness',                 null,                                    'Colin & Melissa',              ARRAY['cmackey@villarecoverynetwork.com','melissa@empowerrecoverynj.com'], 'high',   2,    200,  null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_the_hope',                'The Hope Institute',             'https://thehopeinstitutenj.com/',      'Jason & Dustin',               ARRAY['jason@thehopeinstitutenj.com','dustin@thehopeinstitutenj.com'],     'high',   3,    300,  '2025-07-07', '7th',  'active',  true,  true,  true,  'Cloudflare', null,         null),
('cl_dj_housing',              'DJ Housing',                     null,                                    null,                           ARRAY[]::text[],                                                            'high',   3,    310,  null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_hopeful_estates',         'Hopeful Estates',                null,                                    null,                           ARRAY[]::text[],                                                            'high',   3,    320,  null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_santa_barbara',           'Santa Barbara Recovery',         'https://santabarbararecovery.com/',    'Adam & Colin',                 ARRAY['adam@santabarbararecovery.com','colin@santabarbararecovery.com'],   'high',   4,    400,  '2025-06-23', '23rd', 'active',  true,  true,  true,  'GoDaddy',    null,         null),
('cl_dubai',                   'Dubai',                          null,                                    null,                           ARRAY[]::text[],                                                            'high',   5,    500,  null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_florida_addiction',       'Florida Addiction Hotline',      null,                                    null,                           ARRAY[]::text[],                                                            'medium', 8,    800,  null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_miami_outpatient',        'Miami Outpatient',               'https://miamioutpatientdetox.com/',    null,                           ARRAY['team@scaledai.org'],                                                 'medium', 8,    810,  '2025-11-01', null,   'active',  true,  true,  null,  null,         null,         null),
('cl_tampa_outpatient',        'Tampa Outpatient',               'https://tampaoutpatientdetox.com/',    null,                           ARRAY['team@scaledai.org'],                                                 'medium', 8,    820,  '2025-11-01', null,   'active',  true,  true,  null,  null,         null,         null),
('cl_national_mental_health',  'National Mental Health Support', 'https://nationalmentalhealthsupport.com/', 'Teddy',                    ARRAY['admin@recoverywithus.org','teddy@cruzctrldigital.com','joe@cruzctrldigital.com'], 'medium', 8, 830, '2025-02-03', '1st', 'active', true, false, true,  null,         null,         null),
('cl_national_depression',     'National Depression Hotline',    'https://nationaldepressionhotline.org/', 'Teddy',                      ARRAY['admin@recoverywithus.org'],                                          'medium', 8,    840,  '2025-02-03', '1st',  'active',  true,  false, null,  null,         null,         null),
('cl_alc_awareness',           'Alcohol Awareness',              'https://alcoholawareness.org/',        'Teddy',                        ARRAY['admin@recoverywithus.org','teddy@cruzctrldigital.com','joe@cruzctrldigital.com'], 'medium', 8, 850, '2025-02-03', '1st', 'active', true, false, null, null, null, null),
('cl_florida_sober',           'Florida Sober Living',           null,                                    null,                           ARRAY[]::text[],                                                            'medium', 8,    860,  null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_holas',                   'Get Holas',                      null,                                    'Jason',                        ARRAY['jay@getholas.com'],                                                  'medium', 10,   1000, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_fortify',                 'Fortify Wellness',               'https://fortifywx.com/',               'Chad, Henry, Victor',          ARRAY['chad@fortifywx.com','henry@fortifywx.com','victor@fortifywx.com'],  'medium', 11,   1100, '2025-10-31', '31st', 'active',  false, false, true,  null,         null,         null),
('cl_simonds',                 'Simonds Recovery Centers',       'https://simondsrecoverycenters.com/',  'Henry',                        ARRAY['henry@simondsrecoverycenters.com'],                                  'medium', 12,   1200, '2025-10-28', '28th', 'active',  true,  false, true,  'GoDaddy',    'cPanel',     null),
('cl_pathways',                'Pathways Recovery',              'https://pathwaysrecovery.com/',        'Danita & Michael',             ARRAY['danita@pathwaysrecovery.com','michael@pathwaysrecovery.com'],       'medium', 14,   1400, '2025-12-01', null,   'active',  null,  null,  null,  null,         null,         null),
('cl_eleve',                   'Eleve Wellness',                 'https://eleve-wellness.com/',          'Bibi & Chris',                 ARRAY['bibi@elevewellnessnj.com','chris@elevewellnessnj.com'],             'low',    18,   1800, null,         null,   'pending', null,  null,  null,  null,         null,         null),
('cl_destiny',                 'Destiny Recovery',               'https://destiny-rc.com/',              'Juls, Michael & Stephanie',    ARRAY['julsw@destiny-rc.com','michaelrubin@destiny-rc.com','stephanieh@destiny-rc.com'], 'low', 19, 1900, '2025-10-30', '7th', 'active', false, true, true,  null,         null,         null),
('cl_pinnacle',                'Pinnacle Detox & Recovery',      'https://pinnaclerecovery.org/',        'Karo Kosh',                    ARRAY['help@pinnaclerecovery.org'],                                         'low',    20,   2000, '2025-10-30', '30th', 'active',  false, true,  true,  null,         null,         null),
('cl_pool_websites',           'Pool Websites (Scott)',          'poolspalmbeaches.com',                 'Scott',                        ARRAY['scott@pooldoctorpb.com','scott@primepoolmarket.com','rob@pooldoctorpb.com','jack@innovativeoutdoorliving.com','nick@innovativeoutdoorliving.com'], 'low', 21, 2100, '2024-07-23', '30th', 'active', true, false, null, null, null, null),
('cl_innovative_outdoor',      'Innovative Outdoor Living',      'https://innovativeoutdoorliving.com/', 'Scott',                        ARRAY['scott@pooldoctorpb.com'],                                            'low',    21,   2110, '2024-07-28', '28th', 'active',  true,  false, null,  null,         null,         null),
('cl_pools_palm_beach',        'Pools of Palm Beach',            'poolspalmbeaches.com',                 'Scott',                        ARRAY['scott@pooldoctorpb.com'],                                            'low',    21,   2120, '2024-07-29', '28th', 'active',  true,  false, null,  null,         null,         null),
('cl_schiller_pools',          'Schiller Pools',                 'https://schillerpools.com/',           'Scott',                        ARRAY['scott@pooldoctorpb.com'],                                            'low',    21,   2130, '2024-07-30', '28th', 'active',  true,  false, null,  null,         null,         null),
('cl_cristallo_pools',         'Cristallo Pools',                'https://cristallopools.com/',          'Scott',                        ARRAY['scott@pooldoctorpb.com'],                                            'low',    21,   2140, '2024-07-31', '28th', 'active',  true,  false, null,  null,         null,         null),
('cl_quest2recovery',          'Quest 2 Recovery',               'https://quest2recovery.com/',          'Gaspar',                       ARRAY['gmelikyan@questdetox.com'],                                          'low',    22,   2200, '2025-06-02', '2nd',  'active',  true,  true,  true,  'Cloudflare', 'Cloudflare', null),
('cl_questiop',                'Quest IOP',                      null,                                    'Arthur',                       ARRAY['ablikian@questiop.com'],                                             'low',    23,   2300, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_vive',                    'Vive Treatment Centers',         null,                                    'Seth',                         ARRAY['seth.rosenblatt@vivetreatmentcenters.com'],                          'low',    24,   2400, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_cobb_defense',            'Cobb Defense',                   'https://cobbdefense.com/',             'Gregory',                      ARRAY['gchancy@gmail.com'],                                                 'low',    25,   2500, '2024-12-21', '21st', 'active',  true,  true,  true,  null,         null,         null),
('cl_arise_billing',           'Arise Billing Solutions',        null,                                    null,                           ARRAY[]::text[],                                                            'low',    26,   2600, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_changes_treatment',       'Changes Treatment',              null,                                    'Chris & Phoung',               ARRAY['chris@changestreatment.com','phoung@changestreatment.com'],         'low',    27,   2700, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_chimney_guard',           'Chimney Guard',                  null,                                    null,                           ARRAY[]::text[],                                                            'low',    28,   2800, null,         null,   'active',  null,  null,  null,  null,         null,         null),
-- Unranked but on the master sheet — push to the bottom of the order.
('cl_allocation_assist',       'Allocation Assist',              'https://www.allocationassist.com/',    'Emilie',                       ARRAY['emilie@allocationassist.com','ammar@allocationassist.com','islam@allocationassist.com'], 'low', null, 9000, '2025-07-09', '20th', 'active', true, false, true, 'GoDaddy', null, null),
('cl_northridge_addiction',    'Northridge Addiction',           'https://northridgeaddiction.com/',     'Colin Mackey',                 ARRAY['cmackey@villarecoverynetwork.com'],                                  'low',    null, 9010, '2025-02-03', '1st',  'active',  true,  true,  true,  null,         null,         null),
('cl_project_haven',           'Project Haven',                  'https://projecthaven1.wpenginepowered.com/', 'Cole Taylor',            ARRAY['colet6868@gmail.com'],                                               'low',    null, 9020, '2025-10-31', '31st', 'active',  true,  false, null,  null,         null,         null),
('cl_vf_paving',               'V&F Paving',                     null,                                    'Angelo',                       ARRAY['angelo@vfpaving.com'],                                               'low',    null, 9030, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_creative_closet',         'Creative Closet Design',         null,                                    'Dewayne',                      ARRAY['creativeclosetdesigns1@gmail.com'],                                  'low',    null, 9040, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_nj_drug_resource',        'New Jersey Drug Resource',       'https://newjerseydrugresource.com/',   'Colin & Melissa',              ARRAY['cmackey@villarecoverynetwork.com','melissa@empowerrecoverynj.com'], 'low',    null, 9050, '2025-12-10', '10th', 'active',  true,  true,  null,  null,         null,         null),
('cl_nj_addiction',            'NJ Addiction',                   null,                                    null,                           ARRAY[]::text[],                                                            'low',    null, 9060, null,         null,   'active',  null,  null,  null,  null,         null,         null),
('cl_doctor_finder',           'Doctor Finder',                  'https://doctorsfinder.com/',           'Emilie',                       ARRAY['emilie@allocationassist.com'],                                       'low',    null, 9070, '2026-01-15', null,   'active',  null,  null,  null,  null,         null,         null),
('cl_nj_outpatient',           'New Jersey Outpatient',          'https://newjerseyoutpatientdetox.com/', null,                          ARRAY['team@scaledai.org'],                                                 'low',    null, 9080, '2025-11-01', null,   'active',  true,  true,  null,  null,         null,         null);
